(in-package #:3b-openxr-bindings)
;; API Constants
;; SECTION: OpenXR enumerant (token) definitions.
;; Misc. hardcoded constants - not an enumerated type
;; This is part of the header boilerplate
(defconstant true 1)
;; This is part of the header boilerplate
(defconstant +true+ 1)
(defconstant false 0)
(defconstant +false+ 0)
(defconstant +max-extension-name-size+ 128)
(defconstant +max-api-layer-name-size+ 256)
(defconstant +max-api-layer-description-size+ 256)
(defconstant +max-system-name-size+ 256)
(defconstant +max-application-name-size+ 128)
(defconstant +max-engine-name-size+ 128)
(defconstant +max-runtime-name-size+ 128)
(defconstant +max-path-length+ 256)
(defconstant +max-structure-name-size+ 64)
(defconstant +max-result-string-size+ 64)
(defconstant +max-graphics-apis-supported+ 32)
(defconstant +max-action-set-name-size+ 64)
(defconstant +max-action-name-size+ 64)
(defconstant +max-localized-action-set-name-size+ 128)
(defconstant +max-localized-action-name-size+ 128)

;; #define
(declaim (inline make-version))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun make-version (major minor patch)
    "translate major,minor,patch to an xr version value"
    (check-type major (unsigned-byte 16))
    (check-type minor (unsigned-byte 16))
    (check-type patch (unsigned-byte 32))
    (logior (ash (ldb (byte 16 0) major) 48) (ash (ldb (byte 16 0) minor) 32)
            (ldb (byte 32 0) patch))))
(defun parse-version (version)
  "return components of an xr version as 3 values: major, minor, patch "
  (values (ldb (byte 16 48) version) (ldb (byte 16 32) version)
          (ldb (byte 32 0) version)))
(declaim (inline version-major))
(defun version-major (version) (ldb (byte 16 48) version))
(declaim (inline version-minor))
(defun version-minor (version) (ldb (byte 16 32) version))
(declaim (inline version-patch))
(defun version-patch (version) (ldb (byte 32 0) version))
;; NOTE: The following group of lines defining the two version constants
;;         must not be re-arranged or re-flowed, since scripts/update_version.py
;;         updates them automatically by processing a line at a time.
(defconstant +current-api-version+ (make-version 1 0 27))
(defconstant +null-handle+ 0)
(defconstant +null-path+ 0)
(defconstant +null-system-id+ 0)
(defconstant +no-duration+ 0)
(defconstant +infinite-duration+ #x7fffffffffffffff)
(defconstant +min-haptic-duration+ -1)
(defconstant +frequency-unspecified+ 0)
(defconstant +max-event-data-size+ #.(cffi:foreign-type-size '(:struct event-data-buffer)))
(defconstant +min-composition-layers-supported+ 16)
;; XR_EXT_hand_tracking
(defconstant +hand-joint-count-ext+ 26)
;; XR_MSFT_controller_model
(defconstant +null-controller-model-key-msft+ 0)
;; XR_FB_render_model
(defconstant +null-render-model-key-fb+ 0)
;; XR_HTC_facial_tracking
(defconstant +facial-expression-eye-count-htc+ 14)
(defconstant +facial-expression-lip-count-htc+ 37)
;; XR_ULTRALEAP_hand_tracking_forearm
(defconstant +hand-forearm-joint-count-ultraleap+ 27)
;; XR_FB_haptic_amplitude_envelope
(defconstant +max-haptic-amplitude-envelope-samples-fb+ 4000)
;; XR_FB_haptic_pcm
(defconstant +max-haptic-pcm-buffer-size-fb+ 4000)

;; misc globals
(defconstant khr-android-thread-settings-spec-version 5)
(defparameter khr-android-thread-settings-extension-name "XR_KHR_android_thread_settings")
(defconstant khr-android-surface-swapchain-spec-version 4)
(defparameter khr-android-surface-swapchain-extension-name "XR_KHR_android_surface_swapchain")
(defconstant khr-composition-layer-cube-spec-version 8)
(defparameter khr-composition-layer-cube-extension-name "XR_KHR_composition_layer_cube")
(defconstant khr-android-create-instance-spec-version 3)
(defparameter khr-android-create-instance-extension-name "XR_KHR_android_create_instance")
(defconstant khr-composition-layer-depth-spec-version 6)
(defparameter khr-composition-layer-depth-extension-name "XR_KHR_composition_layer_depth")
(defconstant khr-vulkan-swapchain-format-list-spec-version 4)
(defparameter khr-vulkan-swapchain-format-list-extension-name "XR_KHR_vulkan_swapchain_format_list")
(defconstant ext-performance-settings-spec-version 4)
(defparameter ext-performance-settings-extension-name "XR_EXT_performance_settings")
(defconstant ext-thermal-query-spec-version 2)
(defparameter ext-thermal-query-extension-name "XR_EXT_thermal_query")
(defconstant khr-composition-layer-cylinder-spec-version 4)
(defparameter khr-composition-layer-cylinder-extension-name "XR_KHR_composition_layer_cylinder")
(defconstant khr-composition-layer-equirect-spec-version 3)
(defparameter khr-composition-layer-equirect-extension-name "XR_KHR_composition_layer_equirect")
(defconstant ext-debug-utils-spec-version 4)
(defparameter ext-debug-utils-extension-name "XR_EXT_debug_utils")
(defconstant khr-opengl-enable-spec-version 10)
(defparameter khr-opengl-enable-extension-name "XR_KHR_opengl_enable")
(defconstant khr-opengl-es-enable-spec-version 8)
(defparameter khr-opengl-es-enable-extension-name "XR_KHR_opengl_es_enable")
(defconstant khr-vulkan-enable-spec-version 8)
(defparameter khr-vulkan-enable-extension-name "XR_KHR_vulkan_enable")
(defconstant khr-d3d11-enable-spec-version 9)
(defparameter khr-d3d11-enable-extension-name "XR_KHR_D3D11_enable")
(defconstant khr-d3d12-enable-spec-version 9)
(defparameter khr-d3d12-enable-extension-name "XR_KHR_D3D12_enable")
(defconstant ext-eye-gaze-interaction-spec-version 2)
(defparameter ext-eye-gaze-interaction-extension-name "XR_EXT_eye_gaze_interaction")
(defconstant khr-visibility-mask-spec-version 2)
(defparameter khr-visibility-mask-extension-name "XR_KHR_visibility_mask")
(defconstant extx-overlay-spec-version 5)
(defparameter extx-overlay-extension-name "XR_EXTX_overlay")
(defconstant khr-composition-layer-color-scale-bias-spec-version 5)
(defparameter khr-composition-layer-color-scale-bias-extension-name "XR_KHR_composition_layer_color_scale_bias")
(defconstant khr-win32-convert-performance-counter-time-spec-version 1)
(defparameter khr-win32-convert-performance-counter-time-extension-name "XR_KHR_win32_convert_performance_counter_time")
(defconstant khr-convert-timespec-time-spec-version 1)
(defparameter khr-convert-timespec-time-extension-name "XR_KHR_convert_timespec_time")
(defconstant varjo-quad-views-spec-version 1)
(defparameter varjo-quad-views-extension-name "XR_VARJO_quad_views")
(defconstant msft-unbounded-reference-space-spec-version 1)
(defparameter msft-unbounded-reference-space-extension-name "XR_MSFT_unbounded_reference_space")
(defconstant msft-spatial-anchor-spec-version 2)
(defparameter msft-spatial-anchor-extension-name "XR_MSFT_spatial_anchor")
(defconstant fb-composition-layer-image-layout-spec-version 1)
(defparameter fb-composition-layer-image-layout-extension-name "XR_FB_composition_layer_image_layout")
(defconstant fb-composition-layer-alpha-blend-spec-version 2)
(defparameter fb-composition-layer-alpha-blend-extension-name "XR_FB_composition_layer_alpha_blend")
(defconstant mnd-headless-spec-version 2)
(defparameter mnd-headless-extension-name "XR_MND_headless")
(defconstant oculus-android-session-state-enable-spec-version 1)
(defparameter oculus-android-session-state-enable-extension-name "XR_OCULUS_android_session_state_enable")
(defconstant ext-view-configuration-depth-range-spec-version 1)
(defparameter ext-view-configuration-depth-range-extension-name "XR_EXT_view_configuration_depth_range")
(defconstant ext-conformance-automation-spec-version 3)
(defparameter ext-conformance-automation-extension-name "XR_EXT_conformance_automation")
(defconstant mndx-egl-enable-spec-version 1)
(defparameter mndx-egl-enable-extension-name "XR_MNDX_egl_enable")
(defconstant msft-spatial-graph-bridge-spec-version 2)
(defparameter msft-spatial-graph-bridge-extension-name "XR_MSFT_spatial_graph_bridge")
(defconstant +guid-size-msft+ 16)
(defconstant msft-hand-interaction-spec-version 1)
(defparameter msft-hand-interaction-extension-name "XR_MSFT_hand_interaction")
(defconstant ext-hand-tracking-spec-version 4)
(defparameter ext-hand-tracking-extension-name "XR_EXT_hand_tracking")
(defconstant msft-hand-tracking-mesh-spec-version 4)
(defparameter msft-hand-tracking-mesh-extension-name "XR_MSFT_hand_tracking_mesh")
(defconstant msft-secondary-view-configuration-spec-version 1)
(defparameter msft-secondary-view-configuration-extension-name "XR_MSFT_secondary_view_configuration")
(defconstant msft-first-person-observer-spec-version 1)
(defparameter msft-first-person-observer-extension-name "XR_MSFT_first_person_observer")
(defconstant msft-controller-model-spec-version 2)
(defparameter msft-controller-model-extension-name "XR_MSFT_controller_model")
(defconstant +max-controller-model-node-name-size-msft+ 64)
(defconstant msft-perception-anchor-interop-spec-version 1)
(defparameter msft-perception-anchor-interop-extension-name "XR_MSFT_perception_anchor_interop")
(defconstant ext-win32-appcontainer-compatible-spec-version 1)
(defparameter ext-win32-appcontainer-compatible-extension-name "XR_EXT_win32_appcontainer_compatible")
(defconstant epic-view-configuration-fov-spec-version 2)
(defparameter epic-view-configuration-fov-extension-name "XR_EPIC_view_configuration_fov")
(defconstant msft-holographic-window-attachment-spec-version 1)
(defparameter msft-holographic-window-attachment-extension-name "XR_MSFT_holographic_window_attachment")
(defconstant msft-composition-layer-reprojection-spec-version 1)
(defparameter msft-composition-layer-reprojection-extension-name "XR_MSFT_composition_layer_reprojection")
(defconstant huawei-controller-interaction-spec-version 1)
(defparameter huawei-controller-interaction-extension-name "XR_HUAWEI_controller_interaction")
(defconstant fb-android-surface-swapchain-create-spec-version 1)
(defparameter fb-android-surface-swapchain-create-extension-name "XR_FB_android_surface_swapchain_create")
(defconstant fb-swapchain-update-state-spec-version 3)
(defparameter fb-swapchain-update-state-extension-name "XR_FB_swapchain_update_state")
(defconstant fb-composition-layer-secure-content-spec-version 1)
(defparameter fb-composition-layer-secure-content-extension-name "XR_FB_composition_layer_secure_content")
(defconstant fb-body-tracking-spec-version 1)
(defparameter fb-body-tracking-extension-name "XR_FB_body_tracking")
(defconstant ext-dpad-binding-spec-version 1)
(defparameter ext-dpad-binding-extension-name "XR_EXT_dpad_binding")
(defconstant valve-analog-threshold-spec-version 2)
(defparameter valve-analog-threshold-extension-name "XR_VALVE_analog_threshold")
(defconstant ext-hand-joints-motion-range-spec-version 1)
(defparameter ext-hand-joints-motion-range-extension-name "XR_EXT_hand_joints_motion_range")
(defconstant khr-loader-init-spec-version 1)
(defparameter khr-loader-init-extension-name "XR_KHR_loader_init")
(defconstant khr-loader-init-android-spec-version 1)
(defparameter khr-loader-init-android-extension-name "XR_KHR_loader_init_android")
(defconstant khr-vulkan-enable2-spec-version 2)
(defparameter khr-vulkan-enable2-extension-name "XR_KHR_vulkan_enable2")
(defconstant khr-composition-layer-equirect2-spec-version 1)
(defparameter khr-composition-layer-equirect2-extension-name "XR_KHR_composition_layer_equirect2")
(defconstant ext-samsung-odyssey-controller-spec-version 1)
(defparameter ext-samsung-odyssey-controller-extension-name "XR_EXT_samsung_odyssey_controller")
(defconstant ext-hp-mixed-reality-controller-spec-version 1)
(defparameter ext-hp-mixed-reality-controller-extension-name "XR_EXT_hp_mixed_reality_controller")
(defconstant mnd-swapchain-usage-input-attachment-bit-spec-version 2)
(defparameter mnd-swapchain-usage-input-attachment-extension-name "XR_MND_swapchain_usage_input_attachment_bit")
(defconstant msft-scene-understanding-spec-version 2)
(defparameter msft-scene-understanding-extension-name "XR_MSFT_scene_understanding")
(defconstant msft-scene-understanding-serialization-spec-version 2)
(defparameter msft-scene-understanding-serialization-extension-name "XR_MSFT_scene_understanding_serialization")
(defconstant fb-display-refresh-rate-spec-version 1)
(defparameter fb-display-refresh-rate-extension-name "XR_FB_display_refresh_rate")
(defconstant htc-vive-cosmos-controller-interaction-spec-version 1)
(defparameter htc-vive-cosmos-controller-interaction-extension-name "XR_HTC_vive_cosmos_controller_interaction")
(defconstant htcx-vive-tracker-interaction-spec-version 2)
(defparameter htcx-vive-tracker-interaction-extension-name "XR_HTCX_vive_tracker_interaction")
(defconstant htc-facial-tracking-spec-version 2)
(defparameter htc-facial-tracking-extension-name "XR_HTC_facial_tracking")
(defconstant htc-vive-focus3-controller-interaction-spec-version 2)
(defparameter htc-vive-focus3-controller-interaction-extension-name "XR_HTC_vive_focus3_controller_interaction")
(defconstant htc-hand-interaction-spec-version 1)
(defparameter htc-hand-interaction-extension-name "XR_HTC_hand_interaction")
(defconstant htc-vive-wrist-tracker-interaction-spec-version 1)
(defparameter htc-vive-wrist-tracker-interaction-extension-name "XR_HTC_vive_wrist_tracker_interaction")
(defconstant fb-color-space-spec-version 3)
(defparameter fb-color-space-extension-name "XR_FB_color_space")
(defconstant fb-hand-tracking-mesh-spec-version 3)
(defparameter fb-hand-tracking-mesh-extension-name "XR_FB_hand_tracking_mesh")
(defconstant fb-hand-tracking-aim-spec-version 2)
(defparameter fb-hand-tracking-aim-extension-name "XR_FB_hand_tracking_aim")
(defconstant fb-hand-tracking-capsules-spec-version 3)
(defparameter fb-hand-tracking-capsules-extension-name "XR_FB_hand_tracking_capsules")
(defconstant +hand-tracking-capsule-point-count-fb+ 2)
(defconstant +hand-tracking-capsule-count-fb+ 19)
;; Backward-compatibility alias containing typo.
(defconstant fb-hand-tracking-capsule-point-count 2)
;; Backward-compatibility alias containing typo.
(defconstant fb-hand-tracking-capsule-count 19)
(defconstant fb-spatial-entity-spec-version 2)
(defparameter fb-spatial-entity-extension-name "XR_FB_spatial_entity")
(defconstant fb-foveation-spec-version 1)
(defparameter fb-foveation-extension-name "XR_FB_foveation")
(defconstant fb-foveation-configuration-spec-version 1)
(defparameter fb-foveation-configuration-extension-name "XR_FB_foveation_configuration")
(defconstant fb-keyboard-tracking-spec-version 1)
(defparameter fb-keyboard-tracking-extension-name "XR_FB_keyboard_tracking")
(defconstant +max-keyboard-tracking-name-size-fb+ 128)
(defconstant fb-triangle-mesh-spec-version 2)
(defparameter fb-triangle-mesh-extension-name "XR_FB_triangle_mesh")
(defconstant fb-passthrough-spec-version 3)
(defparameter fb-passthrough-extension-name "XR_FB_passthrough")
(defconstant +passthrough-color-map-mono-size-fb+ 256)
(defconstant fb-render-model-spec-version 3)
(defparameter fb-render-model-extension-name "XR_FB_render_model")
(defconstant +max-render-model-name-size-fb+ 64)
(defconstant khr-binding-modification-spec-version 1)
(defparameter khr-binding-modification-extension-name "XR_KHR_binding_modification")
(defconstant varjo-foveated-rendering-spec-version 3)
(defparameter varjo-foveated-rendering-extension-name "XR_VARJO_foveated_rendering")
(defconstant varjo-composition-layer-depth-test-spec-version 2)
(defparameter varjo-composition-layer-depth-test-extension-name "XR_VARJO_composition_layer_depth_test")
(defconstant varjo-environment-depth-estimation-spec-version 1)
(defparameter varjo-environment-depth-estimation-extension-name "XR_VARJO_environment_depth_estimation")
(defconstant varjo-marker-tracking-spec-version 1)
(defparameter varjo-marker-tracking-extension-name "XR_VARJO_marker_tracking")
(defconstant varjo-view-offset-spec-version 1)
(defparameter varjo-view-offset-extension-name "XR_VARJO_view_offset")
(defconstant ml-ml2-controller-interaction-spec-version 1)
(defparameter ml-ml2-controller-interaction-extension-name "XR_ML_ml2_controller_interaction")
(defconstant ml-frame-end-info-spec-version 1)
(defparameter ml-frame-end-info-extension-name "XR_ML_frame_end_info")
(defconstant ml-global-dimmer-spec-version 1)
(defparameter ml-global-dimmer-extension-name "XR_ML_global_dimmer")
(defconstant ml-compat-spec-version 1)
(defparameter ml-compat-extension-name "XR_ML_compat")
(defconstant msft-spatial-anchor-persistence-spec-version 2)
(defparameter msft-spatial-anchor-persistence-extension-name "XR_MSFT_spatial_anchor_persistence")
(defconstant +max-spatial-anchor-name-size-msft+ 256)
(defconstant ultraleap-hand-tracking-forearm-spec-version 1)
(defparameter ultraleap-hand-tracking-forearm-extension-name "XR_ULTRALEAP_hand_tracking_forearm")
(defconstant fb-spatial-entity-query-spec-version 1)
(defparameter fb-spatial-entity-query-extension-name "XR_FB_spatial_entity_query")
(defconstant fb-spatial-entity-storage-spec-version 1)
(defparameter fb-spatial-entity-storage-extension-name "XR_FB_spatial_entity_storage")
(defconstant oculus-audio-device-guid-spec-version 1)
(defparameter oculus-audio-device-guid-extension-name "XR_OCULUS_audio_device_guid")
(defconstant max-audio-device-str-size-oculus 128)
(defconstant fb-foveation-vulkan-spec-version 1)
(defparameter fb-foveation-vulkan-extension-name "XR_FB_foveation_vulkan")
(defconstant fb-swapchain-update-state-android-surface-spec-version 1)
(defparameter fb-swapchain-update-state-android-surface-extension-name "XR_FB_swapchain_update_state_android_surface")
(defconstant fb-swapchain-update-state-opengl-es-spec-version 1)
(defparameter fb-swapchain-update-state-opengl-es-extension-name "XR_FB_swapchain_update_state_opengl_es")
(defconstant fb-swapchain-update-state-vulkan-spec-version 1)
(defparameter fb-swapchain-update-state-vulkan-extension-name "XR_FB_swapchain_update_state_vulkan")
(defconstant khr-swapchain-usage-input-attachment-bit-spec-version 3)
(defparameter khr-swapchain-usage-input-attachment-extension-name "XR_KHR_swapchain_usage_input_attachment_bit")
(defconstant fb-touch-controller-pro-spec-version 1)
(defparameter fb-touch-controller-pro-extension-name "XR_FB_touch_controller_pro")
(defconstant fb-spatial-entity-sharing-spec-version 1)
(defparameter fb-spatial-entity-sharing-extension-name "XR_FB_spatial_entity_sharing")
(defconstant fb-space-warp-spec-version 2)
(defparameter fb-space-warp-extension-name "XR_FB_space_warp")
(defconstant fb-haptic-amplitude-envelope-spec-version 1)
(defparameter fb-haptic-amplitude-envelope-extension-name "XR_FB_haptic_amplitude_envelope")
(defconstant fb-scene-spec-version 1)
(defparameter fb-scene-extension-name "XR_FB_scene")
(defconstant ext-palm-pose-spec-version 2)
(defparameter ext-palm-pose-extension-name "XR_EXT_palm_pose")
(defconstant almalence-digital-lens-control-spec-version 1)
(defparameter almalence-digital-lens-control-extension-name "XR_ALMALENCE_digital_lens_control")
(defconstant fb-scene-capture-spec-version 1)
(defparameter fb-scene-capture-extension-name "XR_FB_scene_capture")
(defconstant fb-spatial-entity-container-spec-version 2)
(defparameter fb-spatial-entity-container-extension-name "XR_FB_spatial_entity_container")
(defconstant meta-foveation-eye-tracked-spec-version 1)
(defparameter meta-foveation-eye-tracked-extension-name "XR_META_foveation_eye_tracked")
(defconstant +foveation-center-size-meta+ 2)
(defconstant fb-face-tracking-spec-version 1)
(defparameter fb-face-tracking-extension-name "XR_FB_face_tracking")
(defconstant fb-eye-tracking-social-spec-version 1)
(defparameter fb-eye-tracking-social-extension-name "XR_FB_eye_tracking_social")
(defconstant fb-passthrough-keyboard-hands-spec-version 2)
(defparameter fb-passthrough-keyboard-hands-extension-name "XR_FB_passthrough_keyboard_hands")
(defconstant fb-composition-layer-settings-spec-version 1)
(defparameter fb-composition-layer-settings-extension-name "XR_FB_composition_layer_settings")
(defconstant fb-touch-controller-proximity-spec-version 1)
(defparameter fb-touch-controller-proximity-extension-name "XR_FB_touch_controller_proximity")
(defconstant fb-haptic-pcm-spec-version 1)
(defparameter fb-haptic-pcm-extension-name "XR_FB_haptic_pcm")
(defconstant fb-composition-layer-depth-test-spec-version 1)
(defparameter fb-composition-layer-depth-test-extension-name "XR_FB_composition_layer_depth_test")
(defconstant meta-local-dimming-spec-version 1)
(defparameter meta-local-dimming-extension-name "XR_META_local_dimming")
(defconstant oculus-external-camera-spec-version 1)
(defparameter oculus-external-camera-extension-name "XR_OCULUS_external_camera")
(defconstant +max-external-camera-name-size-oculus+ 32)
(defconstant meta-vulkan-swapchain-create-info-spec-version 1)
(defparameter meta-vulkan-swapchain-create-info-extension-name "XR_META_vulkan_swapchain_create_info")
(defconstant meta-performance-metrics-spec-version 2)
(defparameter meta-performance-metrics-extension-name "XR_META_performance_metrics")
(defconstant fb-spatial-entity-storage-batch-spec-version 1)
(defparameter fb-spatial-entity-storage-batch-extension-name "XR_FB_spatial_entity_storage_batch")
(defconstant fb-spatial-entity-user-spec-version 1)
(defparameter fb-spatial-entity-user-extension-name "XR_FB_spatial_entity_user")
(defconstant meta-headset-id-spec-version 1)
(defparameter meta-headset-id-extension-name "XR_META_headset_id")
(defconstant ext-uuid-spec-version 1)
(defparameter ext-uuid-extension-name "XR_EXT_uuid")
(defconstant +uuid-size-ext+ 16)
(defconstant qcom-tracking-optimization-settings-spec-version 1)
(defparameter qcom-tracking-optimization-settings-extension-name "XR_QCOM_tracking_optimization_settings")
(defconstant htc-passthrough-spec-version 1)
(defparameter htc-passthrough-extension-name "XR_HTC_passthrough")
(defconstant htc-foveation-spec-version 1)
(defparameter htc-foveation-extension-name "XR_HTC_foveation")
(defconstant ext-active-action-set-priority-spec-version 1)
(defparameter ext-active-action-set-priority-extension-name "XR_EXT_active_action_set_priority")
(defconstant mndx-force-feedback-curl-spec-version 1)
(defparameter mndx-force-feedback-curl-extension-name "XR_MNDX_force_feedback_curl")
(defconstant bd-controller-interaction-spec-version 1)
(defparameter bd-controller-interaction-extension-name "XR_BD_controller_interaction")
(defconstant ext-local-floor-spec-version 1)
(defparameter ext-local-floor-extension-name "XR_EXT_local_floor")